# Site settings
title: AspenStars
SEOTitle: 星点 | AspenStars Blog
header-img: img/post-bg-coffee.jpeg
email: aspenstars@foxmail.com
description: "谦逊，和善"
keyword: "Deep Learning, UESTC, ICT"
url: "http://aspenstarss.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/aspenstarss/aspenstarss.github.io" # you code repository

author: Aspenstars

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
github_username:    aspenstarss
# facebook_username:  
# jianshu_username:   
#twitter_username:  
#facebook_username:  
#linkedin_username:  firstname-lastname-idxxxx


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: aspenstars

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 10c695caedb7fa1a26e9                           #生成的clientID
  clientSecret: 6edd148ca67d24a2d12f0e3b4e29433edf3198e4    #生成的clientSecret
  repo: aspenstarss.github.io    #仓库名称
  owner: aspenstarss    #github用户名
  admin: aspenstarss
  distractionFreeMode: true #是否启用类似FB的阴影遮罩



# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 384eff9e8354f9d75aeb721667ad20a2

# Google Analytics
#ga_track_id: 'UA-135076059-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "谦逊，和善"
sidebar-avatar: /img/about-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: post preview



# Friends
friends: [
    #{
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
